@startuml
'https://plantuml.com/object-diagram

object user
object reviewUserView
object reviewUserController
object reviews

user -down-> reviewUserView : setRating(), setComment(), reviewUser()
reviewUserView -down-> reviewUserController : reviewUser(reviewData)
reviewUserController -down-> reviews : saveReview(reviewData)

@enduml
