@startuml
'https://plantuml.com/object-diagram

object user
object chatView
object chatController
object messages

user --> chatView : openChat(), setMessage(messageData), addPhoto(photoData), sendMessage()
chatView --> chatController : sendMessage(messageData)
chatController --> messages : saveMessage(messageData)

@enduml
