@startuml
'https://plantuml.com/object-diagram

object user
object usersView
object usersController
object users

user --> usersView : showUsers(kilometers), setKilometers()
usersView --> usersController : getUsers(kilometers)
usersController --> users : getUsers(kilometers)

@enduml
