@startuml

state OPENED_PROFILE

OPENED_PROFILE --> S1 : Player requests add picture
S1 --> S2 : System permits enter picture
S2 --> S3 : Player introduce picture
S3 --> S4 : Player confirms
S3 --> S5 : Player cancels
S4 --> OPENED_PROFILE : System show uploaded message
S5 --> OPENED_PROFILE

@enduml