@startuml

state OPENED_PROFILE
state OPENED_TRAININGS
state OPENED_EXERCISES
state OPENED_PUBLICATIONS
state OPENED_REVIEWS
state OPENED_USERS
state OPENED_CHATS

OPENED_PROFILE --> OPENED_USERS
OPENED_CHATS --> OPENED_USERS
OPENED_TRAININGS --> OPENED_USERS
OPENED_EXERCISES --> OPENED_USERS
OPENED_PUBLICATIONS --> OPENED_USERS
OPENED_REVIEWS --> OPENED_USERS

OPENED_USERS -down-> S1 : System permits enter kilometers
S1 -down-> S2 : User enter kilometers
S2 -up-> OPENED_USERS : System shows all users by kilometers

@enduml