@startuml

!theme crt-green

state INITIAL
state OPENED_PROFILE
state OPENED_EXERCISES
state OPENED_TRAININGS
state OPENED_PUBLICATIONS
state OPENED_PUBLICATION
state OPENED_USERS
state OPENED_REVIEWS
state OPENED_CHATS

[*] --> INITIAL
INITIAL --> OPENED_PROFILE : Login
INITIAL --> OPENED_PROFILE : RegisterUser

OPENED_PROFILE --> OPENED_TRAININGS : ShowTrainings
OPENED_PROFILE --> OPENED_PROFILE : AddPictureToProfile
OPENED_PROFILE --> OPENED_PROFILE : AddSportToProfile
OPENED_TRAININGS --> OPENED_TRAININGS : CreateTraining

OPENED_PROFILE --> OPENED_EXERCISES : ShowExercises
OPENED_EXERCISES --> OPENED_EXERCISES : CreateExercise

OPENED_PROFILE --> OPENED_PUBLICATIONS : ShowPublications
OPENED_PUBLICATIONS --> OPENED_PUBLICATIONS : CreatePublication
OPENED_PUBLICATIONS --> OPENED_PUBLICATION : ShowPublication
OPENED_PUBLICATION --> OPENED_PUBLICATION : CommentPublication

OPENED_PROFILE --> OPENED_USERS : ShowUsersByKilometers

OPENED_PROFILE --> OPENED_REVIEWS : ShowReviews
OPENED_REVIEWS --> OPENED_REVIEWS : ReviewUser

OPENED_PROFILE --> OPENED_CHATS : ShowChats
OPENED_CHATS --> OPENED_MESSAGES : ShowMessages
OPENED_MESSAGES --> OPENED_MESSAGES : SendMessage

@enduml