@startuml

!theme crt-green

class Player
class Review
class Chat
class Message
class Notification

Player --> Review
Player --> Chat
Player --> Notification

Chat --> Message
Review --> Notification
Message --> Notification

@enduml